---
name: deploy
"on":
  push:
    branches:
      - main
jobs:
  build:
    name: wait-apply
    runs-on: ubuntu-latest
    steps:
      -
        name: wait for terraform apply
        uses: actions/tfe-run-wait-action@main
        with:
          action: wait
          token: ${{ secrets.TFE_API_TOKEN }}
          clone-url: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          commit-sha: ${GITHUB_SHA}
          branch: ${GITHUB_REF_NAME}
          organization: ${{ secrets.TFE_ORGANIZATION }}
