---
name: deploy
"on":
  push:
    branches:
      - main
jobs:
  build:
    name: wait-apply
    runs-on: ubuntu-latest
    container: ghcr.io/binxio/tfe-run-wait:0.6.4
    env:
      TFE_API_TOKEN: ${{ secrets.TFE_API_TOKEN }}
    steps:
      - name: wait
        run: >
          tfe-run-wait
          --organization ${{ secrets.TFE_ORGANIZATION }}
          --clone-url ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          --commit-sha ${GITHUB_SHA}
          --branch ${GITHUB_REF_NAME}
          --wait-for policy_checked
          --wait-for planned
          --wait-for applied
