---
name: deploy
"on":
  push:
    branches:
      - main
jobs:
  build:
    name: wait-apply
    runs-on: ubuntu-latest
    steps:
      -
        name: wait for terraform apply
        uses: binxio/tfe-run-wait-action@main
        with:
          action: wait
          branch: main
          commit_sha: ${GITHUB_SHA}
          token: ${{ secrets.TFE_API_TOKEN }}
          clone_url: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          organization: ${{ secrets.TFE_ORGANIZATION }}
